version: "3"

services:
  server:
    image: sonarqube:latest
    network_mode: host
    ports:
      - "9000:9000"

  scanner:
    container_name: sonarscanner
    image: sonarsource/sonar-scanner-cli
    network_mode: host
    volumes:
      - ./:/usr/src
